### ISSUE TITLE
NEED someone to review codes for pull requests!

### ISSUE THREAD

**Issue by LBYPatrick** [LSRobotics/FTC2017#4]
Gordon did not give access to branches, which means that we could only do pull requests. BUT he is so busy that pull requests might not get reviewed on time.

New member required.

**Comment by gordon-zhao** [comment]
Excuse me?

**Comment by tylerliu** [comment]
Not a code issue.

**Comment by LBYPatrick** [comment]
@tylerliu But it is still an issue though

**Comment by tylerliu** [comment]
You are not reading the comment!
